# Generated by Django 4.1.4 on 2022-12-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Linky",
            fields=[
                ("linky_id", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.TextField()),
                ("size", models.TextField()),
                ("level", models.TextField()),
                ("character", models.TextField()),
            ],
            options={
                "db_table": "lingkys",
            },
        ),
    ]
