# Generated by Django 4.1.4 on 2022-12-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mbti", "__first__"),
        ("user", "__first__"),
        ("linky", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("diagnosis_id", models.AutoField(primary_key=True, serialize=False)),
                ("joy", models.TextField()),
                ("sadness", models.TextField()),
                ("anger", models.TextField()),
                ("panic", models.TextField()),
                ("anxiety", models.IntegerField()),
                ("bruise", models.IntegerField()),
                ("personality", models.IntegerField()),
                ("diagnosis_history", models.IntegerField()),
                (
                    "linky",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="linky.linky"
                    ),
                ),
                (
                    "mbti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mbti.mbti"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "diagnosis",
            },
        ),
    ]
